#!/bin/sh
set -e

# TODO: Fix automagical ctags. This would be nice to have if it didn't turn my
# macbook into a jet plane every time I interact with git repos.

# PATH="/usr/local/bin:$PATH"
# dir="`git rev-parse --git-dir`"
# trap 'rm -f "$dir/$$.tags"' EXIT
# git ls-files | \
#   ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
#   mv "$dir/$$.tags" "$dir/tags"

# credit: https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
