#!/usr/bin/env osascript

on run argv
  set desired to item 1 of argv
  set workingApp to (path to frontmost application)

  tell application "System Events" to activate
  tell application "System Events"
    tell appearance preferences
      set dark mode to desired equal to "dark"
    end tell
  end tell

  tell workingApp do
    activate front window
  end tell
end run
