#!/usr/bin/env bash

case "$#" in
  1)
    login=$(git config --get github.user)
    repo="$1"
    ;;
  2)
    login="$1"
    repo="$2"
    ;;
  *)
    echo "Usage: $0 [<login>] <repo_name>"
    exit 1
esac

login_dir="$HOME/dev/$login"
repo_dir="$login_dir/$repo"

# Make sure directory exists
mkdir -p "$repo_dir"
cd "$repo_dir" || exit 1
git init

echo -n "cd $repo_dir" | pbcopy
echo "Hit Command-V + Return to cd into the repo!"
