#!/usr/bin/env bash

if [ -z "$*" ]; then
  git checkout "$(git branch --format='%(refname:short)' | fzf | tr -d '[:space:]')"
else
  git checkout "$(git branch --format='%(refname:short)' | fzf --query "$@" | tr -d '[:space:]')"
fi
